# This is a basic workflow to help you get started with Actions

name: Tabula rasa

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # delete files
      - name: Clear test_file.md
        run: cat /dev/null > test_file.md
      # folders may be missing and fail
      - name: delete folder
        if: always()
        run: rm folder/*
      - name: remake the folder
        if: always()
        run: mkdir folder
      - name: Push changes to repo files
        uses: actions-x/commit@v2
        if: always()
        with:
          name: Github Actions Automation
          branch: main
          files: .
          token: ${{ secrets.GITHUB_TOKEN }}
          force: true
